services:
  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: src/Web.Api/Dockerfile
    depends_on:
      postgres : 
        condition: service_healthy
        restart: true
      seq :
        condition: service_started
        restart: true
    ports:
      - 5000:8080
      - 5001:8081


  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=clean-architecture
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clean-architecture"]
      interval: 10s
      timeout: 5s
      retries: 5

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80


  # for local development : papercut sumulates an SMTP server ( without sending emails )
  # we can view whats happening on port 8080
  # for production u have to specify the real smtp server
  # papercut:
  #   image: changemakerstudiosus/papercut-smtp:latest
  #   container_name: papercut
  #   ports:
  #     - 8080:80
  #     - 25:25
  #     25 for local smtp server
